# Generated by Django 4.2.7 on 2025-10-25 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del trolley (ej: Trolley de Bebidas, Trolley de Comida)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del trolley', null=True)),
                ('airline', models.CharField(help_text='Aerolínea', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trolley',
                'verbose_name_plural': 'Trolleys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrolleyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(choices=[(1, 'Nivel 1 (Superior)'), (2, 'Nivel 2 (Medio)'), (3, 'Nivel 3 (Inferior)')], help_text='Número del nivel')),
                ('capacity', models.IntegerField(default=20, help_text='Capacidad máxima de artículos en este nivel')),
                ('description', models.TextField(blank=True, help_text='Descripción o notas del nivel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='trolleys.trolley')),
            ],
            options={
                'verbose_name': 'Nivel del Trolley',
                'verbose_name_plural': 'Niveles del Trolley',
                'ordering': ['level_number'],
                'unique_together': {('trolley', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='TrolleyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del artículo', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del artículo', null=True)),
                ('sku', models.CharField(help_text='SKU único del artículo', max_length=100, unique=True)),
                ('quantity', models.IntegerField(help_text='Cantidad de unidades disponibles', validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Imagen del artículo', null=True, upload_to='trolley_items/%Y/%m/%d/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del artículo', max_digits=10, null=True)),
                ('category', models.CharField(blank=True, help_text='Categoría del artículo (ej: Bebida, Snack, Comida)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trolleys.trolleylevel')),
            ],
            options={
                'verbose_name': 'Artículo del Trolley',
                'verbose_name_plural': 'Artículos del Trolley',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['sku'], name='trolleys_tr_sku_fd6a10_idx'), models.Index(fields=['level'], name='trolleys_tr_level_i_b1aebe_idx')],
            },
        ),
    ]
