# Generated by Django 4.2.7 on 2025-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='ID de la estación', max_length=255)),
                ('flight_number', models.CharField(help_text='Número de vuelo', max_length=255)),
                ('customer_name', models.CharField(help_text='Nombre del cliente/aerolínea', max_length=255)),
                ('drawer_id', models.CharField(help_text='ID del drawer/gaveta', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos QR',
                'verbose_name_plural': 'Datos QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
