# Generated by Django 4.2.7 on 2025-10-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0002_qrdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='trolleys',
            field=models.ManyToManyField(help_text='Trolleys asignados a este vuelo', related_name='flights', to='trolleys.trolley'),
        ),
    ]
