# Generated by Django 4.2.7 on 2025-10-26 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0003_qrdata_trolleys'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrolleyDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawer_id', models.CharField(help_text='ID único del drawer (ej: DRW_013)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción o notas del drawer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='trolleys.trolleylevel')),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawers', to='trolleys.trolley')),
            ],
            options={
                'verbose_name': 'Drawer del Trolley',
                'verbose_name_plural': 'Drawers del Trolley',
                'ordering': ['trolley', 'drawer_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(help_text='ID del stream de datos', max_length=255)),
                ('timestamp', models.DateTimeField(help_text='Tiempo exacto de la lectura')),
                ('station_id', models.CharField(help_text='ID de la estación', max_length=255)),
                ('spec_id', models.CharField(help_text='ID de especificación', max_length=255)),
                ('sensor_type', models.CharField(choices=[('camera', 'Cámara'), ('barcode', 'Código de Barras'), ('rfid', 'RFID'), ('scale', 'Báscula'), ('other', 'Otro')], help_text='Tipo de sensor', max_length=50)),
                ('expected_value', models.CharField(blank=True, help_text='Valor esperado según especificación', max_length=255)),
                ('detected_value', models.CharField(blank=True, help_text='Valor detectado por el sensor', max_length=255)),
                ('deviation_score', models.FloatField(default=0, help_text='Puntuación de desviación (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('alert_flag', models.CharField(choices=[('OK', 'OK'), ('Alert', 'Alerta')], default='OK', help_text='Indicador de alerta', max_length=10)),
                ('operator_id', models.CharField(blank=True, help_text='ID del operador', max_length=255)),
                ('flight_number', models.CharField(help_text='Número de vuelo', max_length=255)),
                ('customer_name', models.CharField(help_text='Nombre del cliente/aerolínea', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawer', models.ForeignKey(blank=True, help_text='Drawer del que proviene la lectura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_data', to='trolleys.trolleydrawer')),
            ],
            options={
                'verbose_name': 'Dato de Sensor',
                'verbose_name_plural': 'Datos de Sensores',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='trolleydrawer',
            index=models.Index(fields=['drawer_id'], name='trolleys_tr_drawer__a21d37_idx'),
        ),
        migrations.AddIndex(
            model_name='trolleydrawer',
            index=models.Index(fields=['trolley'], name='trolleys_tr_trolley_c7610c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['drawer'], name='trolleys_se_drawer__64179b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['timestamp'], name='trolleys_se_timesta_e679ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['flight_number'], name='trolleys_se_flight__f5660e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['alert_flag'], name='trolleys_se_alert_f_f497a7_idx'),
        ),
    ]
