# Generated by Django 4.2.7 on 2025-10-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0005_rename_trolleyitem_product_and_new_specification_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='specificationitem',
            name='unique_spec_item_per_drawer',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='trolleys_pr_sku_b83575_idx',
            old_name='trolleys_pr_sku_abcdef_idx',
        ),
        migrations.AlterUniqueTogether(
            name='specificationitem',
            unique_together={('specification', 'drawer', 'product')},
        ),
    ]
